# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
df = pd.read_csv("/content/data_clustering_inverse.csv")

In [3]:
# Tampilkan 5 baris pertama dengan function head.
df.head()

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Target
0,14.09,Debit,San Diego,ATM,Senior,Doctor,81.0,1.0,5112.21,0
1,376.24,Debit,Houston,ATM,Senior,Doctor,141.0,1.0,13758.91,2
2,126.29,Debit,Mesa,Online,Youth,Student,56.0,1.0,1122.35,2
3,184.50,Debit,Raleigh,Online,Youth,Student,25.0,1.0,8569.06,0
4,13.45,Credit,Atlanta,Online,Adult,Student,198.0,1.0,7429.40,1

In [4]:
# Melakukan feature encoding untuk fitur kategorikal
categorical_cols = ['TransactionType', 'Location', 'Channel', 'CustomerAge', 'CustomerOccupation']
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le
df.head()

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Target
0,14.09,1,36,0,1,0,81.0,1.0,5112.21,0
1,376.24,1,15,0,1,0,141.0,1.0,13758.91,2
2,126.29,1,23,2,2,3,56.0,1.0,1122.35,2
3,184.50,1,33,2,2,3,25.0,1.0,8569.06,0
4,13.45,0,1,2,0,3,198.0,1.0,7429.40,1

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [5]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = df.drop('Target', axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(2010, 9) (503, 9)
(2010,) (503,)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [6]:
# Buatlah model klasifikasi menggunakan Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [8]:
# Menyimpan Model
# import joblib
joblib.dump(dt_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [9]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [10]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
y_pred_dt = dt_model.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='weighted')
recall_dt = recall_score(y_test, y_pred_dt, average='weighted')
f1_dt = f1_score(y_test, y_pred_dt, average='weighted')

y_pred_rf = rf_model.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf, average='weighted')
recall_rf = recall_score(y_test, y_pred_rf, average='weighted')
f1_rf = f1_score(y_test, y_pred_rf, average='weighted')
y_pred = rf_model.predict(X_test)

# Buat tabel perbandingan
data_metrik = {
    'Decision Tree': [accuracy_dt, precision_dt, recall_dt, f1_dt],
    'Random Forest': [accuracy_rf, precision_rf, recall_rf, f1_rf]
}
metrics_df = pd.DataFrame(data_metrik, index=['Akurasi', 'Presisi', 'Recall', 'F1-Score'])
print("Tabel Metrik untuk Semua Model:\n", metrics_df)
print("\nClassification Report Decision Tree:\n", classification_report(y_test, y_pred_dt))
print("\nClassification Report Random Forest:\n", classification_report(y_test, y_pred_rf))

Tabel Metrik untuk Semua Model:
           Decision Tree  Random Forest
Akurasi             1.0            1.0
Presisi             1.0            1.0
Recall              1.0            1.0
F1-Score            1.0            1.0

Classification Report Decision Tree:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       175
           1       1.00      1.00      1.00       155
           2       1.00      1.00      1.00       173

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503


Classification Report Random Forest:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       175
           1       1.00      1.00      1.00       155
           2       1.00      1.00      1.00       173

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503

In [11]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
joblib.dump(rf_model, 'explore_RandomForest_classification.h5')

['explore_RandomForest_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [12]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.
param_dist = {
    'n_estimators': [50, 100, 150, 200, 250],
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10, 15]
}

random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train, y_train)

print("Parameter Terbaik:", random_search.best_params_)
print("Skor Terbaik:", random_search.best_score_)

Parameter Terbaik: {'n_estimators': 200, 'min_samples_split': 2, 'max_depth': None}
Skor Terbaik: 1.0

In [13]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
best_model = random_search.best_estimator_
y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

data_metrik = {
    'Random Forest (After Tunning)': ['Akurasi', 'Presisi', 'Recall', 'F1-Score'],
    'Skor': [accuracy, precision, recall, f1]
}
tabel_metrik = pd.DataFrame(data_metrik)
tabel_metrik = tabel_metrik.set_index('Random Forest (After Tunning)')

print(tabel_metrik)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

                               Skor
Random Forest (After Tunning)
Akurasi                         1.0
Presisi                         1.0
Recall                          1.0
F1-Score                        1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       175
           1       1.00      1.00      1.00       155
           2       1.00      1.00      1.00       173

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503

In [14]:
# Menyimpan Model hasil tuning
# import joblib
joblib.dump(best_model, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code